### ISSUE TITLE
Drifting crafting window

### ISSUE THREAD

**Issue by AlphaM01** [Tk420634/Para-Arf#34]
**Problem Description**:
Crafting interface doesn't show up on the right spot and keeps drifting away from the screen, making it unusable after only being opened a few times.

**What did you expect to happen**: 
For it to appear roughly at the center of the screen.

**What happened instead**:
It appears slightly too far up, leaving the close and minimize buttons outside of the screen.

**Why is this bad/What are the consequences:**
It can still be closed with Alt+F4 but every time it's opened it drifts further and further up until it's unusable, and eventually, completely outside of the screen. With the top bar gone from the first time it's opened, it's impossible to drag it back down. It's position can be reset by closing the game window and joining the server again.

**Steps to reproduce the problem**:
Open crafting screen. Close. Repeat.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Screen resolution used is 1366x768, does it in both maximized and windowed mode.

**Comment by AnonymousHybi** [comment]
Odd, have you tried using windows key + up arrow to maximis the crafting window?

**Comment by AlphaM01** [comment]
I have, no effect.
Also, it seems the same thing is also happening to other bits of UI.
Namely, having the exact same problem with the crew monitoring screen.

**Comment by AnonymousHybi** [comment]
What operating system are you running?

**Comment by AlphaM01** [comment]
Win 10, 64 bit.

**Comment by AnonymousHybi** [comment]
Sorry mate, cannot fix this issue. The reason why it goes up is because the window's position is made in the bottom left corner of the window, and resizing the window to make it smaller, and closing and opening it, causes it to save the position of where it used to be. But didn't keep it's resolution. So for you it might scroll up.

Users using any screen which is less than 900 or 800 pixels might encounter this issue, and it's an issue on how BYOND handles it's HTML output.
